baseurl = "http://josiahandchelsea.com/"
languageCode = "en-us"
title = "Josiah and Chelsea are Getting Married!"
theme = "skel"
copyright = "Josiah Gaskin 2015. All rights reserved."

[params]
  banner = "Josiah and Chelsea are Getting Married!"
  tagline = ""
  name = "JosiahAndChelsea.com"

[[params.actions]]
  action = "https://docs.google.com/forms/d/14LBR7qbNfYrak8HikXvWacJTlNMt4yDNjBkmCFTGEtE/viewform"
  class = "special"
  title = "RSVP"
